name: 'Attach next milestone'
description: 'Attach next open milestone to a merged PR'

inputs:
  token:
    description: 'A Github personal authentication token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get PR number
      id: pr
      shell: bash
      run: >-
        echo "::set-env name=PR::$(
          jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH"
        )"

    - name: Get next milestone
      id: milestone
      shell: bash
      run: >-
        python -m pip install requests ;
        echo "::set-env name=MILESTONE::$(
          python next-milestone.py $GITHUB_REPOSITORY
        )"

    - name: Attach milestone to PR
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        python set-pr-milestone.py $GITHUB_REPOSITORY $PR $MILESTONE
