name: 'Attach next milestone'
description: 'Attach next open milestone to a merged PR'

inputs:
  token:
    description: 'A Github personal authentication token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get PR number
      id: pr
      shell: bash
      run: >-
        echo "PR=$(
          jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH"
        )" >> $GITHUB_ENV

    - name: Get next milestone
      id: milestone
      shell: bash
      run: >-
        python -m pip install requests ;
        echo "MILESTONE=$(
          python ${{ github.action_path }}/next-milestone.py $GITHUB_REPOSITORY
        )" >> $GITHUB_ENV

    - name: Attach milestone to PR
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        python ${{ github.action_path }}/set-pr-milestone.py $GITHUB_REPOSITORY $PR $MILESTONE
